"""Object storage for uploaded PDFs. PDFs are never stored in Postgres (SPEC.md §5).

Two implementations behind one protocol: local disk for development, Cloudflare R2 for production.
R2 is S3-compatible, so boto3 talks to it unchanged.

The reason this is an interface rather than a direct boto3 call: it lets ingest be built and tested
before the bucket exists, and it keeps the "how do we serve a PDF to the browser" question in one
place. That question has a non-obvious answer — see `signed_url` below.

Files are stored under a GENERATED key, never under the user-supplied filename (SPEC.md §7.4).
Uploaded PDFs are untrusted input, and a filename is an injection vector like any other.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Protocol
from uuid import UUID

import boto3
from botocore.config import Config

from clause.config import REPO_ROOT, settings


class Storage(Protocol):
    def put(self, key: str, data: bytes) -> None: ...

    def get(self, key: str) -> bytes: ...

    def delete(self, key: str) -> None: ...

    def signed_url(self, key: str, *, expires_in: int = 3600) -> str:
        """A URL the BROWSER fetches the PDF from directly.

        This is the whole reason object storage earns its place. The PDF viewer needs the bytes; if
        they lived in Postgres, every page load would wake the database and stream 10 MB through the
        API container. With a signed URL the browser goes straight to Cloudflare, and neither our
        container nor our database is in the path (ROADMAP.md §5.1).
        """
        ...


def storage_key(document_id: UUID) -> str:
    """Generated, never derived from the filename."""
    return f"documents/{document_id}.pdf"


class LocalStorage:
    """Development. Writes under .local-storage/, which .gitignore excludes."""

    def __init__(self, root: Path | None = None) -> None:
        self.root = root or (REPO_ROOT / ".local-storage")
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        # A key is generated by us, not supplied by a user — but this is the cheap check that keeps
        # it that way if someone later wires a user-controlled string into it.
        if not path.is_relative_to(self.root.resolve()):
            raise ValueError(f"storage key escapes the storage root: {key!r}")
        return path

    def put(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def get(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)

    def signed_url(self, key: str, *, expires_in: int = 3600) -> str:
        # In development the API serves the bytes itself. In production it never does.
        return f"/api/documents/local/{key}"

    def reset(self) -> None:
        shutil.rmtree(self.root, ignore_errors=True)


class R2Storage:
    """Production. Cloudflare R2 — S3-compatible, free tier, and no egress fees, which matters
    because serving PDFs to a browser IS egress."""

    def __init__(self) -> None:
        s = settings()
        self.bucket = s.r2_bucket
        self.client = boto3.client(
            "s3",
            endpoint_url=f"https://{s.r2_account_id}.r2.cloudflarestorage.com",
            aws_access_key_id=s.r2_access_key_id,
            aws_secret_access_key=s.r2_secret_access_key,
            config=Config(signature_version="s3v4"),
            region_name="auto",
        )

    def put(self, key: str, data: bytes) -> None:
        self.client.put_object(
            Bucket=self.bucket, Key=key, Body=data, ContentType="application/pdf"
        )

    def get(self, key: str) -> bytes:
        obj = self.client.get_object(Bucket=self.bucket, Key=key)
        return obj["Body"].read()

    def delete(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=key)

    def signed_url(self, key: str, *, expires_in: int = 3600) -> str:
        return self.client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self.bucket, "Key": key},
            ExpiresIn=expires_in,
        )


def get_storage() -> Storage:
    s = settings()
    if s.r2_account_id and s.r2_access_key_id:
        return R2Storage()
    return LocalStorage()
