/** The pre-computed demo analyses, imported straight into the bundle.
 *
 * This is the whole reason the demo is free and instant (SPEC.md §7.1, ROADMAP.md §5.2): these are
 * JSON files produced by `python -m clause.demo`, and importing them here means clicking a sample
 * makes ZERO API calls and touches no backend at all. The free container can be asleep and the demo
 * still works — which matters, because the demo is the primary call to action and its fifteen-second
 * budget has no room in it for a cold start.
 *
 * They are aliased from ../../demo/precomputed (see vite.config.ts) rather than copied, so there is
 * one source of truth shared with the backend. Re-bake them with `cd api && uv run python -m
 * clause.demo` whenever the prompt, the rules, or the scan model changes — otherwise the demo shows
 * the output of a system that no longer exists.
 */

import saasMsa from "@demo/saas_msa.json";
import salesforceMsa from "@demo/salesforce_msa.json";
// `?url` gives us the built asset's URL rather than its contents. Vite emits the PDF into the bundle
// (hashed filename) and serves it statically, so the source PDF is still part of the no-backend demo
// — a visitor can open the actual contract and check a quote against it, which is the whole point of
// the product's "every quote provably exists in the document" claim (SPEC.md §4.5).
import saasPdf from "@demo/saas_msa.pdf?url";
import salesforcePdf from "@demo/salesforce_msa.pdf?url";
import type { DemoAnalysis } from "@/types";

// The JSON is generated by our own pipeline against a known schema, so the assertion is safe; TS
// would otherwise infer wildly specific literal types from the file contents.
export const DEMOS: DemoAnalysis[] = [
  saasMsa as unknown as DemoAnalysis,
  salesforceMsa as unknown as DemoAnalysis,
];

// The source contract for each demo, keyed by slug. Same files the agent actually read.
export const DEMO_PDFS: Record<string, string> = {
  saas_msa: saasPdf,
  salesforce_msa: salesforcePdf,
};

export function demoBySlug(slug: string): DemoAnalysis | undefined {
  return DEMOS.find((d) => d.slug === slug);
}
