import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { fileURLToPath, URL } from "node:url";

// The SPA is a static build. It talks to the FastAPI backend over HTTP for everything dynamic
// (signup, login, upload) — and to nothing at all for the demo, which is pre-computed JSON imported
// straight into the bundle. See ROADMAP.md §2.1 / §5.2: the demo must not wait for a sleeping
// container to wake up, so the backend is deliberately not in that path.
export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      // The pre-computed demo analyses live at the repo root, outside this package, because they are
      // generated by `python -m clause.demo` and are shared with the backend. Aliased rather than
      // copied so there is exactly one source of truth for them.
      "@demo": fileURLToPath(new URL("../demo/precomputed", import.meta.url)),
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  server: {
    port: 5173,
    fs: {
      // Vite refuses to serve files outside the project root unless told otherwise. The demo JSON is
      // one directory up, so the dev server needs this to import it.
      allow: [".."],
    },
  },
});
